---
name: Close inactive issues
on:
  schedule:
    - cron: 30 2 * * 2
  workflow_dispatch:
jobs:
  close-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v9
        with:
          days-before-stale: 180
          days-before-close: 30
          exempt-issue-labels: bug
          exempt-pr-labels: bug
          stale-issue-label: stale
          stale-pr-label: stale
          stale-issue-message: This issue has been marked 'stale' due to lack of activity. The issue will be closed in another 30 days.
          close-issue-message: This issue has been closed due to inactivity. If you feel this is in error, please reopen the issue or file a new issue with the relevant details.
          stale-pr-message: This pr has been marked 'stale' due to lack of recent activity.The issue will be closed in another 30 days.
          close-pr-message: This pr has been closed due to inactivity. If you feel this is in error, please reopen the issue or file a new issue with the relevant details.
          repo-token: ${{ secrets.GITHUB_TOKEN }}
